### ISSUE TITLE
Comparison of two runs

### ISSUE THREAD

**Issue by faulk-lab** [wdecoster/kyber#4]
How exactly did you compare two runs? I tried feeding it two bam files but it did not work.
`/kyber -t 32 -p -o out.png file1.bam file2.bam`

**Comment by wdecoster** [comment]
It is always helpful if you have an error message or some more information than "it did not work". I think this might be related to https://github.com/wdecoster/kyber/issues/3

Could you try `kyber --phred -o out.png --color red blue file1.bam file2.bam`

**Comment by faulk-lab** [comment]
I upgraded to version 0.3.1 and now it's reporting a different error.
```
./kyber -t 32 --phred -o kyber-compare2.png --color red blue file1.hg38.modmapped.bam file2.hg38.modmapped.bam
error: invalid value 'file1.hg38.modmapped.bam' for '--color [<COLOR>...]'
  [possible values: red, green, blue, purple, yellow]

For more information, try '--help'.
```

**Comment by wdecoster** [comment]
I think I understand what the problem is, but I won't have access to the computer for the weekend. Could you try putting the color argument at the end?

**Comment by faulk-lab** [comment]
That solved one problem but created another. I ran `./kyber -t 32 --phred -o kyber-compare2.png file1.hg38.modmapped.bam file2.hg38.modmapped.bam --color red blue` which successfully generated an image with red color only. It matches what I see when I run file1 alone, but it does not include the color or data for file2 that I see when I run file2 alone.

**Comment by wdecoster** [comment]
I'm sorry for the inconvenience, and I will get back to you about this :)

**Comment by wdecoster** [comment]
Hmmm, remarkably enough, running `./kyber -t 32 --phred -o kyber-compare2.png file1.bam file2.bam --color red blue` on my system results in an image with blue, red, and purple (as expected). I'm unsure how to explain what you report, but I will look into it. I also have to fix your previous problem (https://github.com/wdecoster/kyber/issues/4#issuecomment-1), as your command line was of course valid.

**Comment by wdecoster** [comment]
It took me a long time to get back to this - but I think I fixed the problem by making the input file(s) use a -i/--input argument, rather than just being a positional argument.
