### ISSUE TITLE
ERROR could not get max value of histogram

### ISSUE THREAD

**Issue by givdieri** [wdecoster/kyber#7]
I'm running into an error trying to compare some .bam files, the full backtrace is added.

command (kyber v0.3.1)
kyber -t 12 --phred -o kyber-compare.png file1.bam bc01_file2.bam --color red blue

thread 'main' panicked at 'ERROR could not get max value of histogram', src/main.rs:87:14
stack backtrace:
   0:     0x55eeaac2f00a - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55eeaac2f00a - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55eeaac2f00a - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55eeaac2f00a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55eeaac502be - core::fmt::write::h93e2f5923c7eca08
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:     0x55eeaac2c7e5 - std::io::Write::write_fmt::h8162dbb45f0b9e62
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:     0x55eeaac2edd5 - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55eeaac2edd5 - std::sys_common::backtrace::print::hcb5e6388b9235f41
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55eeaac305bf - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:     0x55eeaac302fb - std::panicking::default_hook::h68fa2ba3c3c6c12f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:     0x55eeaac30cc9 - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:688:13
  11:     0x55eeaac30a69 - std::panicking::begin_panic_handler::{{closure}}::hf33414f5dabf6faf
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
  12:     0x55eeaac2f4bc - std::sys_common::backtrace::__rust_end_short_backtrace::hc50389427413bb75
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55eeaac30772 - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  14:     0x55eeaa821de3 - core::panicking::panic_fmt::h2de7a7938f816de8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  15:     0x55eeaac4e381 - core::panicking::panic_display::h20dbb78c57df5693
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:147:5
  16:     0x55eeaac4e32b - core::panicking::panic_str::hb46d5710e4ab412a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:131:5
  17:     0x55eeaa821da6 - core::option::expect_failed::h0b5d04c30548770b
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:1924:5
  18:     0x55eeaa838a0a - kyber::main::hf58cd75b1d8474d8
  19:     0x55eeaa82b2e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha6eed2ca1d658472
  20:     0x55eeaa82e7d9 - std::rt::lang_start::{{closure}}::h4e7d0e1250002a0a
  21:     0x55eeaac2820c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h699977d052768608
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:287:13
  22:     0x55eeaac2820c - std::panicking::try::do_call::h4e121e623c70f903
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  23:     0x55eeaac2820c - std::panicking::try::hf9d919e062bc178a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  24:     0x55eeaac2820c - std::panic::catch_unwind::h7a7b12272684cb97
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  25:     0x55eeaac2820c - std::rt::lang_start_internal::{{closure}}::hd96b0eb4844b8762
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:48
  26:     0x55eeaac2820c - std::panicking::try::do_call::h1af1f88f4f92a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
  27:     0x55eeaac2820c - std::panicking::try::hf20d7abea7f0f097
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
  28:     0x55eeaac2820c - std::panic::catch_unwind::hb0e084c3a9c042e4
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
  29:     0x55eeaac2820c - std::rt::lang_start_internal::hca9d5c7277f5b67c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:20
  30:     0x55eeaa83be75 - main
  31:     0x7f26c4d53d90 - <unknown>
  32:     0x7f26c4d53e40 - __libc_start_main
  33:     0x55eeaa822425 - _start
  34:                0x0 - <unknown>

**Comment by givdieri** [comment]
> Could you share your input files? Does kyber work when you try the files one by one? Could one of the files be (nearly) empty?

Hi,

I can't share - but your comment made me try your test files. Those work like a charm!
The error also occurs when fed one file, so it seems something's wrong with my input.
It doesn't seem related to file-size (tried with 0.5 GB).
Thanks for your reply!

**Comment by wdecoster** [comment]
Hmm, that is remarkable. I would still like to figure out what is the problem with your files. Is there anything more you can tell me (here or through email) about those? Which species, sequencing method, aligner, or any filtering of reads could affect the results?

**Comment by givdieri** [comment]
Sure!

Here are the specifics:
environmental samples, fungal full ITS amplicon (+- 700bp) , sequenced on ONT nanopore, basecalled on dorado v0.1.1., filtered on seq. length >=450, not sorted, not aligned.
The files I'm trying to compare are duplex reads - but the problem persists for simplex reads.

I can share a small downsampled file (duplex reads):

[small.zip](https://github.com/wdecoster/kyber/files/11320428/small.zip)

**Comment by wdecoster** [comment]
Aha, kyber expects aligned reads (to be able to calculate the reference identity). That explains it.

**Comment by givdieri** [comment]
Makes sense, thanks for the clarification!

**Comment by wdecoster** [comment]
I should add a more informative error message there
