### ISSUE TITLE
On white background image not colored

### ISSUE THREAD

**Issue by NikoLichi** [wdecoster/kyber#8]
Hi Wouter,

I am trying to find the best way to see matching colors and have tried both white and black backgrounds. However, with the same setup on a white background, there are no colors; please see the attached figure.

![68_T00_GeneCvsNovo](https://github.com/wdecoster/kyber/assets/19077113/59a72b30-55d1-443a-8b6e-0b2892131515)

Is this a bug?

The code I am using is:
```
./kyber -t 16 \
--input $FILEIN_1 $FILEIN_2 \
--phred \
--background white \
--color red blue \
--output ${PREFIX}_GeneCvsNovo.png

```

Thanks and all the best,
Niko

**Comment by wdecoster** [comment]
Hmm, this looks like a bug. Just to be sure, everything is alright when you use the black background?

**Comment by NikoLichi** [comment]
Yes, everything is normal see the attached figure.

Do you have any suggestions on the phred or the normalized option to check technical replicates?

![65_T00_GeneCvsNovo](https://github.com/wdecoster/kyber/assets/19077113/7adcef40-9637-47e5-aacb-35a56740c92f)

**Comment by NikoLichi** [comment]
Hi Wouter,

I was checking the files again and discovered that what I thought was black is actually a high saturation. I meant, if you make Zoom on the image with white background it is possible to see the red, blue and purple colors. 

However, I would think that even in high saturation the overlapping colors should be kept, in this case purple and not black, or? 

So, I guess Kyber is doing what it should! But the issue with the black color of overlapping points is weird to me.

All the best,
Niko

**Comment by wdecoster** [comment]
Finally fixed, will make a new release soon

**Comment by wdecoster** [comment]
Please let me know if you have other feedback :)
