### ISSUE TITLE
No reads found in BAM file

### ISSUE THREAD

**Issue by lmolokin** [wdecoster/kyber#9]
It looks like kyber currently doesn't like bam files with unaligned reads:
```
kyber -p -c green -i EXP-PBC096_barcode01.bam 

thread 'main' panicked at 'No reads found in BAM file EXP-PBC096_barcode01.bam', src/extract_data.rs:39:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Do you plan to add a --ubam flag like in cramino?

Thanks for your work!
Aleksey

**Comment by wdecoster** [comment]
Hi Aleksey,

kyber plots the percent identity against the read length, and the percent identity is unavailable without alignment. Do you have a use case for which alignment is not an option, then?

Best,
Wouter

**Comment by lmolokin** [comment]
Got it. I don't have a compelling use case I was just thinking it could be used as a speedier alternative to NanoPlot for avg read quality vs length. We don't really have decent references for our organisms so our basecalling doesn't usually involve alignment. 

Thanks!

**Comment by wdecoster** [comment]
So a solution would be for you to trust the read quality scores assigned by the basecaller? I guess that would be possible.

**Comment by wdecoster** [comment]
--ubam will be available in the next release, coming soon :)
